Processing started. Please wait. This may take a few minutes...<br>

--------------------------------------------------------------------------------------<br>
ALEAPP v3.3.0: ALEAPP Logs, Events, and Protobuf Parser<br>
Objective: Triage Android Full System Extractions.<br>
By: Alexis Brignoni | @AlexisBrignoni | abrignoni.com<br>
By: Yogesh Khatri   | @SwiftForensics | swiftforensics.com
<br>
Building files listing...<br>
File listing complete - 623 files<br>
Info: 290 modules loaded.<br>
Artifact categories to parse: 289<br>
File/Directory selected: \\?\O:\forensic\data\com.strava<br>

--------------------------------------------------------------------------------------<br>
<br>
Strava [StravaGPS] artifact started<br>
Processing data for Strava FIT Files<br>
Internet connection is available.<br>
Reading Strava artifact had errors!<br>
Error was cannot access local variable 'file' where it is not associated with a value<br>
Exception Traceback: Traceback (most recent call last):
  File "O:\forensic\Aleapp\ALEAPP\aleapp.py", line 378, in crunch_artifacts
    plugin.method(files_found, category_folder, seeker, wrap_text, time_offset)
  File "O:\forensic\Aleapp\ALEAPP\scripts\artifacts\StravaGPS.py", line 256, in get_gps
    report.write_artifact_data_table(data_headers, data_list, file, html_escape=False, table_id='Strava')
                                                              ^^^^
UnboundLocalError: cannot access local variable 'file' where it is not associated with a value
<br>
<br>
Processes completed.<br>
Processing time = 00:00:00<br>
Processing time (wall)= 00:00:01<br>
<br>
Report generation started.<br>
Report generation Completed.<br>
<br>
Report location: O:\forensic\data\ALEAPP_FORENSIC_DATA_PROCESSING\ALEAPP_Reports_2025-04-09_Wednesday_132802<br>
